### ISSUE TITLE
Desperate student #HTML #XML

### ISSUE THREAD

**Issue by clemmis83** [COST-ELTeC/ELTeC-srp#2]
Hello everybody!

I am a language student, and for some reason my uni asked me to code a French play to HTML and XML TEI.

As you may have noticed from the title, I cannot do that by my own because I do not understand anything.

I thought that maybe some of you could help!

I have attached the Word document which is the extract of the play that I have to code.

Thank you so much!

[doc à  convertir encodage exam final.docx](https://github.com/COST-ELTeC/ELTeC-srp/files/5624066/doc.a.convertir.encodage.exam.final.docx)

**Comment by lb42** [comment]
Try tei-fr. We don't offer consultancy here.
